version: '3.8'

networks:
  grafana:
  timescaledb:
  elastic:

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    command: postgres -c shared_preload_libraries=timescaledb
    networks:
      - grafana
      - timescaledb
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/timescaledb
      - POSTGRES_DB=dbname
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  grafana:
    image: grafana/grafana:10.0.2
    networks:
      - grafana
      - timescaledb
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    networks:
      - elastic
    ports:
      - "9200:9200"
    environment: ['CLI_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false']
     
    volumes:
      - esdata:/usr/share/elasticsearch/data
  
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.12.0
    networks:
      - elastic
    ports:
      - "5601:5601"
    environment: 
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: d1a66dfd-c4d3-4a0a-8290-2abcb83ab3aa
 

volumes:
  esdata: